---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 8678c927f548e8ddcbe8d8142cb73ef3919b837b
    app.quarkus.io/build-timestamp: 2022-05-19 - 12:02:18 +0000
  labels:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: as-rest-server2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8090
  selector:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 8678c927f548e8ddcbe8d8142cb73ef3919b837b
    app.quarkus.io/build-timestamp: 2022-05-19 - 12:02:18 +0000
  labels:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: as-rest-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: as-rest-server2
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 8678c927f548e8ddcbe8d8142cb73ef3919b837b
        app.quarkus.io/build-timestamp: 2022-05-19 - 12:02:18 +0000
      labels:
        app.kubernetes.io/name: as-rest-server2
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: mthirion/as-rest-server2:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: as-rest-server2
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP
