---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
    app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: as-rest-server2
    app.openshift.io/runtime: quarkus
  name: as-rest-server2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
    app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
  labels:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: as-rest-server2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8090
  selector:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: as-rest-server2-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: as-rest-server2
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
    app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: as-rest-server2
    app.openshift.io/runtime: quarkus
  name: as-rest-server2
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
    app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: as-rest-server2
    app.openshift.io/runtime: quarkus
  name: as-rest-server2
spec:
  output:
    to:
      kind: ImageStreamTag
      name: as-rest-server2:1.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:latest
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
    app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: as-rest-server2
    app.openshift.io/runtime: quarkus
  name: as-rest-server2
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: as-rest-server2
    app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 62d38e27d3d842b0fefb698b62748f30640b2b07
        app.quarkus.io/build-timestamp: 2022-05-21 - 09:38:07 +0000
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: as-rest-server2
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: mthirion/as-rest-server2:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: as-rest-server2
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP
      serviceAccount: as-rest-server2
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - as-rest-server2
        from:
          kind: ImageStreamTag
          name: as-rest-server2:1.0-SNAPSHOT
      type: ImageChange
